In [1]:
#import pytorch
import torch
import numpy as np
print(torch.__version__)#pytorch version

2.6.0+cpu


In [3]:
scalar = torch.tensor(7)#tensor(a container for numbers) 
print(scalar)#scalar means number
print(scalar.ndim)#dimension does tensor have
print(scalar.item())#gets actual number

tensor(7)
0
7


In [4]:
vector = torch.tensor([7, 7])#vector is 1-dimensional tensor
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [5]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [7]:
#Higher-dimensional tensor
TENSOR = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6]],
    
    [[7, 8, 9],
     [10, 11, 12]]
])

print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)#in the form of layers rows columns

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])


In [8]:
random_tensor = torch.rand(3, 4)#random tensor
print(random_tensor)
print(random_tensor.shape)

tensor([[0.8144, 0.2600, 0.7529, 0.1591],
        [0.1465, 0.1470, 0.2825, 0.3558],
        [0.5436, 0.5973, 0.2886, 0.8010]])
torch.Size([3, 4])


In [10]:
#image tensor
random_image_tensor = torch.rand(
    size=(224, 224, 3)#RGB
)

print(random_image_tensor.shape)

torch.Size([224, 224, 3])


In [11]:
random_image_tensor = torch.rand(
    size=(3, 224, 224)#chaneels * height * width
)

print(random_image_tensor.shape)


torch.Size([3, 224, 224])


In [12]:
zeros = torch.zeros(size=(3, 4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [13]:
ones = torch.ones(size=(3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
one_to_ten = torch.arange(
    start=1,
    end=11,
    step=1
)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [15]:
ten_zeros = torch.zeros_like(#creates zeros with the same shape
    input=one_to_ten
)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [16]:
float_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float32
)

print(float_tensor)
print(float_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [18]:
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)#where is the tensor stored

tensor([[0.7175, 0.7347, 0.6525, 0.1977],
        [0.4142, 0.3734, 0.5461, 0.6204],
        [0.6708, 0.5081, 0.8636, 0.9086]])
torch.Size([3, 4])
torch.float32
cpu


In [19]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)
print(tensor / 10)
print(torch.add(tensor, 10))
print(torch.mul(tensor, 10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])
tensor([11, 12, 13])
tensor([10, 20, 30])


In [27]:
tensor = torch.tensor([1, 2, 3])
print(torch.matmul(tensor, tensor))
print(tensor @ tensor)
tensor_a = torch.tensor([
    [1, 2],
    [3, 4]
])
tensor_b = torch.tensor([
    [5, 6],
    [7, 8]
])
print(torch.matmul(tensor_a, tensor_b))

tensor(14)
tensor(14)
tensor([[19, 22],
        [43, 50]])


In [20]:
x = torch.arange(1, 10)
print(x)
print(torch.min(x))
print(torch.max(x))
print(torch.mean(x.float()))
print(torch.sum(x))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(1)
tensor(9)
tensor(5.)
tensor(45)


In [21]:
x = torch.tensor([1, 5, 3, 8, 2])
print(torch.argmin(x))#smallest value
print(torch.argmax(x))#largest value

tensor(0)
tensor(3)


In [25]:
x = torch.arange(1, 10)
x_reshaped = x.reshape(1, 9)#change the shape
print(x_reshaped)
print(x_reshaped.shape)
x_reshaped = x.reshape(3, 3)
print(x_reshaped)
print(x_reshaped.shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [26]:
x = torch.arange(1, 10)
x_view = x.view(3, 3)# another way to view the same data
print(x_view)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [27]:
x = torch.tensor([1, 2, 3])
x_stacked = torch.stack(#combines multiple tensors
    [x, x, x],
    dim=0
)
print(x_stacked)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


In [28]:
x = torch.zeros(1, 1, 3)
print(x)
print(x.shape)
x_squeezed = x.squeeze()#removes dimension whose size is 1
print(x_squeezed)
print(x_squeezed.shape)

tensor([[[0., 0., 0.]]])
torch.Size([1, 1, 3])
tensor([0., 0., 0.])
torch.Size([3])


In [29]:
x = torch.tensor([1, 2, 3])
print(x.shape)
x_unsqueezed = x.unsqueeze(dim=0)#adds a dimension
print(x_unsqueezed)
print(x_unsqueezed.shape)
x_unsqueezed = x.unsqueeze(dim=1)
print(x_unsqueezed)
print(x_unsqueezed.shape)

torch.Size([3])
tensor([[1, 2, 3]])
torch.Size([1, 3])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


In [30]:
x = torch.rand(224, 224, 3)
print(x.shape)
x_permuted = x.permute(2, 0, 1)#rearranges the dimension
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [31]:
x = torch.arange(1, 10).reshape(1, 3, 3)#tensor indexing
print(x)
print(x[0])
print(x[0][0])
print(x[0][0][0])
print(x[:, 0])
print(x[:, :, 0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor([[1, 2, 3]])
tensor([[1, 4, 7]])


In [32]:
array = np.arange(1.0, 8.0)#numpy to pytorch
tensor = torch.from_numpy(array)
print(array)
print(tensor)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [34]:
tensor = torch.ones(7)
array = tensor.numpy()
print(tensor)
print(array)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]


In [35]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3, 4)
print(random_tensor_a)
print(random_tensor_b)
print(torch.equal(random_tensor_a, random_tensor_b))

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
True


In [36]:
print(torch.cuda.is_available())#checks whether cuda is compatable with gpu
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
tensor = torch.tensor(
    [1, 2, 3],
    device=device
)
print(tensor)
print(tensor.device)

False
cpu
tensor([1, 2, 3])
cpu


In [39]:
tensor_cpu = tensor.cpu()
print(tensor_cpu)

tensor([1, 2, 3])


In [40]:
x = torch.rand(3, 3)
print("Tensor:")
print(x)
print("Shape:")
print(x.shape)
print("Datatype:")
print(x.dtype)
print("Device:")
print(x.device)
print("Minimum:")
print(x.min())
print("Maximum:")
print(x.max())
print("Mean:")
print(x.mean())
print("Sum:")
print(x.sum())

Tensor:
tensor([[0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895]])
Shape:
torch.Size([3, 3])
Datatype:
torch.float32
Device:
cpu
Minimum:
tensor(0.2814)
Maximum:
tensor(0.9464)
Mean:
tensor(0.6052)
Sum:
tensor(5.4464)


In [41]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.rand(3, 3).to(device)
print(x)
print(x.device)
y = torch.rand(3, 3).to(device)
result = torch.matmul(x, y)
print(result)

tensor([[0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581]])
cpu
tensor([[0.4758, 0.7063, 0.2388],
        [0.5110, 0.8866, 0.4809],
        [0.9080, 1.1161, 0.8163]])
